global:
  scrape_interval: 5s # default is 1 minute

scrape_configs:
  - job_name: caddy
    static_configs:
      - targets: ["caddy:2019"]

  - job_name: ping-pong
    static_configs:
      - targets: ["ping-pong:8000"]